name: Build Jekyll Site

on:
  push:
    branches:
      - main  # Запускать на каждое изменение в ветке main

jobs:
  build:
    runs-on: ubuntu-latest  # Сборка запускается на Ubuntu

    steps:
    - name: Checkout repository  # Скачиваем код репозитория
      uses: actions/checkout@v3

    - name: Set up Python  # Устанавливаем Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Ruby  # Устанавливаем Ruby для Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Python dependencies  # Создаём виртуальную среду и устанавливаем зависимости
      run: |
        python3 -m venv backend/venv
        source backend/venv/bin/activate
        pip install -r backend/requires.txt

    - name: Install Ruby dependencies  # Устанавливаем Jekyll и его плагины
      run: bundle install

    - name: Build Jekyll Site  # Сборка сайта с помощью Jekyll
      run: bundle exec jekyll build

